### ISSUE TITLE
Dating is off 

### ISSUE THREAD

**Issue by Greigh** [ScriptTiger/scripttiger.github.io#3]
How often do you update these? It seems to be off the original list.

**Comment by ScriptTiger** [comment]
Thanks for your interest! I just bumped it to the latest. I've been maintaining this repository for the last several years now and have been updating it pretty regularly. If you'd like to see the "Data Sources Sync" commit history, you can access that from here:
https://github.com/ScriptTiger/scripttiger.github.io/commits/master/

If you need something updated more regularly, I'd recommend downloading Steven Black's hosts Python script and just running that locally. There is no one single "original list," as the script aggregates multiple sources and can be run as frequently as you desire. I also make a Google Colab available to the public, which is also linked on Steven's README, which allows you to generate the list yourself in the cloud using Google Colab, if you don't have Python set up locally.
